### ISSUE TITLE
Linking fail when migrate from 4.0.5 to 4.1.10

### ISSUE THREAD

**Issue by RealThanhpv** [husker-dev/openglfx#96] opened 2024-12-24 06:26 UTC
Hi, I am trying to migrate but hitting this error. 
`Exception in thread "JavaFX Application Thread" java.lang.UnsatisfiedLinkError: C:\Users\blueg\AppData\Local\Temp\1735021374479#com-huskerdev-grapl-core-native-lib-2.3.2-x64.dll: %1 is not a valid Win32 application
`

**Comment by husker-dev** [comment] 2024-12-24 07:17
Hi!
Could you describe your environment in more detail? 
Dependencies, JDK version, module usage (or not), and OS version.

Because everything works for me :)

![image](https://github.com/user-attachments/assets/c07be790-8008-46f2-96cc-0454bfd0ddb9)

**Comment by RealThanhpv** [comment] 2024-12-24 07:42
This is my OS
![image](https://github.com/user-attachments/assets/d23f4b8f-5cbc-4070-a64c-7262704a627f)

JDK: GraalVM 23.0.1-graal,
It is modular

**Comment by RealThanhpv** [comment] 2024-12-24 07:43
Is the source of your sample which you are showing available?

**Comment by husker-dev** [comment] 2024-12-24 07:44
> Is the source of your sample which you are showing available?

Yes, but it needs to be upgraded to 4.1.10
https://github.com/husker-dev/openglfx-example

**Comment by husker-dev** [comment] 2024-12-24 08:18
I checked on a project with modules - everything works fine.

If you still encounter this problem, check the project classpath. 
The libraries should look like this

![image](https://github.com/user-attachments/assets/12f21e03-1149-49c7-9a26-9414b8613a88)

**Comment by RealThanhpv** [comment] 2024-12-24 08:22
Mine 
![image](https://github.com/user-attachments/assets/8b88b433-d9ee-4edb-a0fe-a4a0cb782027)

**Comment by husker-dev** [comment] 2024-12-24 08:29
Then try to check the existence of this file at runtime by reading it somewhere.

If an error occurs, it means that this library is not visible at runtime.

```java
try {
    Main.class.getResourceAsStream("/com/huskerdev/grapl/gl/native/lib-2.3.2-x64.dll").read();
}catch (Throwable e){
    e.printStackTrace();
}
```

![image](https://github.com/user-attachments/assets/defaa42a-773f-4c68-af55-d03777097e1c)

**Comment by RealThanhpv** [comment] 2024-12-24 08:34
Yes!
```
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read()" because the return value of "java.lang.Class.getResourceAsStream(String)" is null
        at gridx.lwjgl@1.0.0/gridx.lwjgl.Launcher.main(Launcher.java:13)
```

**Comment by husker-dev** [comment] 2024-12-24 08:36
Then check your dependencies and classpath again. 
I don't know how it works in Maven, but in Gradle you may have these libraries as `compileOnly`.

**Comment by RealThanhpv** [comment] 2024-12-24 09:52
I do not know why, there something wrong with maven deps:
```
[WARNING] There are 9 pathException(s). The related dependencies will be ignored.
[WARNING] Dependency: C:\Users\blueg\.m2\repository\com\huskerdev\grapl-native-gl-macos\2.3.2\grapl-native-gl-macos-2.3.2.jar
   - exception: Unable to derive module descriptor for C:\Users\blueg\.m2\repository\com\huskerdev\grapl-native-gl-macos\2.3.2\grapl-native-gl-macos-2.3.2.jar
   - cause: grapl.native.gl.macos: Invalid module name: 'native' is not a Java identifier
[WARNING] Dependency: C:\Users\blueg\.m2\repository\com\huskerdev\openglfx-native-core-macos\4.1.10\openglfx-native-core-macos-4.1.10.jar
   - exception: Unable to derive module descriptor for C:\Users\blueg\.m2\repository\com\huskerdev\openglfx-native-core-macos\4.1.10\openglfx-native-core-macos-4.1.10.jar
   - cause: openglfx.native.core.macos: Invalid module name: 'native' is not a Java identifier
[WARNING] Dependency: C:\Users\blueg\.m2\repository\com\huskerdev\grapl-native-core-linux\2.3.2\grapl-native-core-linux-2.3.2.jar
   - exception: Unable to derive module descriptor for C:\Users\blueg\.m2\repository\com\huskerdev\grapl-native-core-linux\2.3.2\grapl-native-core-linux-2.3.2.jar
   - cause: grapl.native.core.linux: Invalid module name: 'native' is not a Java identifier
[WARNING] Dependency: C:\Users\blueg\.m2\repository\com\huskerdev\grapl-native-core-win\2.3.2\grapl-native-core-win-2.3.2.jar
   - exception: Unable to derive module descriptor for C:\Users\blueg\.m2\repository\com\huskerdev\grapl-native-core-win\2.3.2\grapl-native-core-win-2.3.2.jar
   - cause: grapl.native.core.win: Invalid module name: 'native' is not a Java identifier
[WARNING] Dependency: C:\Users\blueg\.m2\repository\com\huskerdev\grapl-native-gl-linux\2.3.2\grapl-native-gl-linux-2.3.2.jar
   - exception: Unable to derive module descriptor for C:\Users\blueg\.m2\repository\com\huskerdev\grapl-native-gl-linux\2.3.2\grapl-native-gl-linux-2.3.2.jar
   - cause: grapl.native.gl.linux: Invalid module name: 'native' is not a Java identifier
[WARNING] Dependency: C:\Users\blueg\.m2\repository\com\huskerdev\openglfx-native-core-win\4.1.10\openglfx-native-core-win-4.1.10.jar
   - exception: Unable to derive module descriptor for C:\Users\blueg\.m2\repository\com\huskerdev\openglfx-native-core-win\4.1.10\openglfx-native-core-win-4.1.10.jar
   - cause: openglfx.native.core.win: Invalid module name: 'native' is not a Java identifier
[WARNING] Dependency: C:\Users\blueg\.m2\repository\com\huskerdev\openglfx-native-core-linux\4.1.10\openglfx-native-core-linux-4.1.10.jar
   - exception: Unable to derive module descriptor for C:\Users\blueg\.m2\repository\com\huskerdev\openglfx-native-core-linux\4.1.10\openglfx-native-core-linux-4.1.10.jar
   - cause: openglfx.native.core.linux: Invalid module name: 'native' is not a Java identifier
[WARNING] Dependency: C:\Users\blueg\.m2\repository\com\huskerdev\grapl-native-gl-win\2.3.2\grapl-native-gl-win-2.3.2.jar
   - exception: Unable to derive module descriptor for C:\Users\blueg\.m2\repository\com\huskerdev\grapl-native-gl-win\2.3.2\grapl-native-gl-win-2.3.2.jar   
   - cause: grapl.native.gl.win: Invalid module name: 'native' is not a Java identifier
[WARNING] Dependency: C:\Users\blueg\.m2\repository\com\huskerdev\grapl-native-core-macos\2.3.2\grapl-native-core-macos-2.3.2.jar
   - exception: Unable to derive module descriptor for C:\Users\blueg\.m2\repository\com\huskerdev\grapl-native-core-macos\2.3.2\grapl-native-core-macos-2.3.2.jar
   - cause: grapl.native.core.macos: Invalid module name: 'native' is not a Java identifier
[WARNING] Can't extract module name from grapl-native-gl-macos-2.3.2.jar: grapl.native.gl.macos: Invalid module name: 'native' is not a Java identifier      
[WARNING] Can't extract module name from openglfx-native-core-macos-4.1.10.jar: openglfx.native.core.macos: Invalid module name: 'native' is not a Java identifier
[WARNING] Can't extract module name from grapl-native-core-linux-2.3.2.jar: grapl.native.core.linux: Invalid module name: 'native' is not a Java identifier  
[WARNING] Can't extract module name from grapl-native-core-win-2.3.2.jar: grapl.native.core.win: Invalid module name: 'native' is not a Java identifier      
[WARNING] Can't extract module name from grapl-native-gl-linux-2.3.2.jar: grapl.native.gl.linux: Invalid module name: 'native' is not a Java identifier      
[WARNING] Can't extract module name from openglfx-native-core-win-4.1.10.jar: openglfx.native.core.win: Invalid module name: 'native' is not a Java identifier
[WARNING] Can't extract module name from openglfx-native-core-linux-4.1.10.jar: openglfx.native.core.linux: Invalid module name: 'native' is not a Java identifier
[WARNING] Can't extract module name from grapl-native-gl-win-2.3.2.jar: grapl.native.gl.win: Invalid module name: 'native' is not a Java identifier
[WARNING] Can't extract module name from grapl-native-core-macos-2.3.2.jar: grapl.native.core.macos: Invalid module name: 'native' is not a Java identifier 
```

**Comment by husker-dev** [comment] 2024-12-24 09:57
Maven doesn't seem to like the word `native`...
Can you give me a minimal version so that I can reproduce it myself?

**Comment by RealThanhpv** [comment] 2024-12-24 11:53
You can change to 4.1.10, now it is running fine with 4.0.5
https://github.com/RealThanhpv/openglfx-sample

**Comment by husker-dev** [comment] 2024-12-24 12:52
I think it is related to modules, because it launches without `module-info.java`. 
I will try to dig into it.

<img width="471" alt="image" src="https://github.com/user-attachments/assets/71046b57-e02e-48e7-a60e-7ad69087643d" />

**Comment by husker-dev** [comment] 2024-12-25 00:17
Fixed in 4.1.14

**Comment by husker-dev** [comment] 2024-12-25 00:17
it took much longer than expected

**Closed by husker-dev** 2024-12-25 00:17 UTC
Labels: question

**Comment by RealThanhpv** [comment] 2024-12-25 02:41
Could you please make a PR of your fix to the repo https://github.com/RealThanhpv/openglfx-sample ? You seems made some change to the animator.

**Comment by RealThanhpv** [comment] 2024-12-25 03:11
The version 4.0.5 I can use the Animator to control rendering. Lets say I wanted to stop rendering (fps = 0) to save energy but keep the last rendered image. This seems to to be related to your new implementation with buffer swap. Could you give me some instruction to stop swapping and then stop rendering. And when I turn on rendering (fps > 0), I turn on the swapping?

**Comment by husker-dev** [comment] 2024-12-25 06:54
To control the FPS you should use "fps" property in GLCanvas. 
Please see "FPS control" in README.MD

**Comment by RealThanhpv** [comment] 2024-12-25 08:17
I mean to stop swapping to keep the old rendered image before turning the fps to 0. How can I get that?

**Comment by husker-dev** [comment] 2024-12-25 08:25
I don't quite understand what you want.

If you want to control the frames, then set `fps` to 0, and call `repaint()` on the canvas when you want to.

But this will not save you from cases when the canvas size changes - the draw call will still occur.

To strictly limit it to one frame, you will need to write all this in the rendering listener. 
openglfx is not made for such work.
