### ISSUE TITLE
Multi-thread rendering

### ISSUE THREAD

**Issue by qq1053831109** [husker-dev/openglfx#41] opened 2023-09-29 12:40 UTC
Opengl latency can affect fx latency. Can they run on different threads? And provide a synchronization mechanism after rendering is completed

**Comment by husker-dev** [comment] 2023-09-29 12:52
In theory this is possible. I'll look into ways to implement it soon.

**Comment by husker-dev** [comment] 2023-11-05 21:27
I did some tests. They show that rendering on another thread is not as efficient as it might seem. Perhaps it's a matter of synchronizing internal data in OpenGL. 

@qq1053831109 Why do you need this functionality?

**Comment by qq1053831109** [comment] 2023-11-06 03:06
You can learn Javafx. The logical thread is n+1 frames.Efficient synchronization mechanism requires excellent design。My opengl panel is for rendering games. Each frame consumes 10ms

**Comment by qq1053831109** [comment] 2023-11-06 03:08
And I need to render multiple opengl panels in one Javafx, such as batch viewing models. I don't want them to share a thread for rendering. This can lead to delays. The client software has a low tolerance for latency.

**Comment by husker-dev** [comment] 2023-11-06 10:45
@qq1053831109 
I've added multi-thread support to the d3d pipeline (i.e. Windows only). 
Also, for now it works only with lwjgl.

---
You can build openglfx by yourself and test performance in your case.

1. Clone project
2. ```./gradlew :compileJars```
3. Add libraries from ```./build/libs``` to your project
4. Change canvas creation:
```kotlin
val canvas = OpenGLCanvas.create(LWJGL_MODULE, multiThread = true)
```

**Comment by qq1053831109** [comment] 2023-11-07 01:56
Need ES2 pipeline, can double buffering be considered? In situations where rendering time is high, synchronization time is less important

**Comment by husker-dev** [comment] 2023-11-07 16:36
Added es2 support. Tomorrow I'll try to do it for sw. 
There are currently some artifacts when resizing the Canvas. I'll try to solve them soon.

**Comment by husker-dev** [comment] 2023-11-19 20:19
Added sw support. 
There is a new interop for macOS is coming, so the issue is not closed.

**Comment by husker-dev** [comment] 2023-11-20 11:22
Added async IOSurface interop.
I will close this issue.

**Closed by husker-dev** 2023-11-20 11:22 UTC
Labels: internal-graphics, enhancement
